In [1]:
input = [1,2,3,4]
output = [5,10,15,20]


In [2]:
w = 0.0
b = 0.0
lr = 0.01

### Perceptron

In [3]:
for epoch in range(100):
    total_loss = 0
    for x,y in zip(input,output):
        y_pred = w*x+b
        error = y_pred-y
        loss = error**2
        total_loss = total_loss + loss

        dw = 2*error*x
        db = 2*error

        w = w - lr*dw
        b = b - lr*db

    if epoch % 10 ==0:
        print(f"epoch: {epoch} | Loss: {total_loss} | w : {w} | b: {b}")

test_data = 10
prediction = w*test_data + b
print(prediction)

epoch: 0 | Loss: 499.2475747664 | w : 2.4274063999999997 | b: 0.8450616
epoch: 10 | Loss: 1.4479377882840494 | w : 4.564153295302238 | b: 1.3991839758571667
epoch: 20 | Loss: 1.1265827746390078 | w : 4.6167160361314314 | b: 1.2333376493523351
epoch: 30 | Loss: 0.8749307188685276 | w : 4.662226746316064 | b: 1.0868937977709436
epoch: 40 | Loss: 0.6794911508750556 | w : 4.702333249048192 | b: 0.9578382600627838
epoch: 50 | Loss: 0.5277083247131091 | w : 4.73767758783982 | b: 0.8441065118479858
epoch: 60 | Loss: 0.4098303202518899 | w : 4.768825212417848 | b: 0.7438790378841708
epoch: 70 | Loss: 0.31828357358030857 | w : 4.796274432010711 | b: 0.6555523683759157
epoch: 80 | Loss: 0.2471862822369721 | w : 4.820464387632196 | b: 0.5777134262387806
epoch: 90 | Loss: 0.19197050428591736 | w : 4.84178207759383 | b: 0.5091169202597802
49.042322020306905


### Neural Network with hidden layer

In [4]:
input = [1,2,3,4,5]
output = [2,4,6,8,10]

In [5]:
w1,b1 = 0.1,0.0
w2,b2 = -0.1,0.0
w3,w4 = 0.1,0.1
b3 = 0.0
lr = 0.01

In [6]:
def relu(input):
    return max(0,input)

In [7]:
def relu_derivative(x):
    return 1 if x>0 else 0

![Neural Network](NN-euron.png)

In [8]:
for epoch in range(100):
    total_loss = 0

    for x,y in zip(input,output):
        z1 = w1*x+b1
        h1 = relu(z1)

        z2 = w2*x+b2
        h2 = relu(z2)

        y_pred = w3*h1 + w4*h2 + b3
        error = y_pred-y
        loss = error*2
        total_loss = total_loss+loss

        dl_dy = 2*error

        dw3 = h1 * dl_dy
        dw4 = h2 * dl_dy
        db3 = dl_dy

        dz1 = dl_dy* w3 * relu_derivative(z1)
        dz2 =  dl_dy *w4 * relu_derivative(z2)

        dw1 = dz1 * x
        db1 = dz1

        dw2 = dz2 * x
        db2 = dz2 

        w1 = w1 - lr*dw1
        w2 = w2 - lr*dw2
        w3 = w3 - lr*dw3
        w4 = w4 - lr*dw4

        b1 = b1 - lr*db1
        b2 = b2 - lr*db2
        b3 = b3 - lr*db3

    
    if epoch%10 ==0:
        print(f"epoch: {epoch} | Loss: {total_loss} | ")


def prediction(x):
    z1 = w1*x + b1
    h1 = relu(z1)

    z2 = w2*x + b2
    h2 = relu(z2)

    y_pred = h1*w3+ h2*w4 + b3
    return y_pred

prediction(9)

epoch: 0 | Loss: -57.32711358807556 | 
epoch: 10 | Loss: 1.498565332580334 | 
epoch: 20 | Loss: 0.9086149949326066 | 
epoch: 30 | Loss: 0.5347310903410438 | 
epoch: 40 | Loss: 0.3084170693559898 | 
epoch: 50 | Loss: 0.17568168683626695 | 
epoch: 60 | Loss: 0.0993383268795629 | 
epoch: 70 | Loss: 0.055932533449965405 | 
epoch: 80 | Loss: 0.03141695114899967 | 
epoch: 90 | Loss: 0.017622666048168867 | 


17.99692772369434

In [9]:
import tensorflow as tf
import numpy as np

In [10]:
x = np.array(input,dtype=float)
y = np.array(output,dtype=float)

In [11]:
model = tf.keras.Sequential([tf.keras.layers.Dense(30,activation="relu",input_shape=[1]),
                    tf.keras.layers.Dense(1)])



c:\One-Drive\OneDrive - Tredence\Euron-GenAI-\euronvenv\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [12]:
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.01),loss="mean_squared_error")

In [13]:
model.fit(x,y,epochs=300,verbose=1)
model.predict(np.array([9]))

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 313ms/step - loss: 45.4574
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - loss: 14.9079
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 3.0058
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.2106
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0435
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0410
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0402
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0394
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0386
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 0.0379
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.0372
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 0.0364
Epoch 13/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - loss: 0.0357
Epoch 14/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - loss: 0.0351
Epoch 15/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0344
Epoch 16/300


array([[17.960724]], dtype=float32)

### RNN - LSTM

In [30]:
data = "help"
char2idx = {'h':0,'e':1,'l':2,'p':3}
idx2char = {v:k for k,v in char2idx.items()}


In [31]:
input_seq = [char2idx[c] for c in data[:-1]]
target_seq = [char2idx[c] for c in data[1:]]

In [32]:
x = tf.one_hot(input_seq,depth=4)
x = tf.expand_dims(x,axis=0)
y = tf.expand_dims(target_seq,axis=0)

In [38]:
x

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)>

In [33]:
y

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [34]:
model_lstm = tf.keras.Sequential([tf.keras.layers.LSTM(8,return_sequences=True,input_shape=(3,4)),
                     tf.keras.layers.Dense(4,activation='linear')])


In [35]:
model_lstm.compile(optimizer="adam",loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))

In [36]:
for epoch in range(301):
    model_lstm.train_on_batch(x,y)

    if epoch%50 == 0:
        output = model_lstm(x)
        print(output)
        pred = tf.argmax(output,axis=-1).numpy()[0]
        pred_char = "".join([idx2char[i] for i in pred])
        print(f"epoch: {epoch} , prediction : {pred_char}, loss: {loss}")

tf.Tensor(
[[[-0.02381544 -0.03854365  0.0102562  -0.02956723]
  [-0.08202262 -0.03088806  0.00631753 -0.09521408]
  [ 0.0735674   0.01576163 -0.03701973 -0.08630554]]], shape=(1, 3, 4), dtype=float32)
epoch: 0 , prediction : llh, loss: -0.0015262807402187661
tf.Tensor(
[[[-0.12557086  0.03177185  0.14024377  0.04054092]
  [-0.23410398  0.00677663  0.25164828 -0.00707807]
  [-0.0657821   0.02678751  0.1317971   0.09377848]]], shape=(1, 3, 4), dtype=float32)
epoch: 50 , prediction : lll, loss: -0.0015262807402187661
tf.Tensor(
[[[-0.2526978   0.0999576   0.2571923   0.09116485]
  [-0.45245516  0.0279357   0.5433848   0.08728951]
  [-0.24889773  0.00344843  0.32518196  0.31693694]]], shape=(1, 3, 4), dtype=float32)
epoch: 100 , prediction : lll, loss: -0.0015262807402187661
tf.Tensor(
[[[-0.4098621   0.17913318  0.3340615   0.1269952 ]
  [-0.77293634  0.02800867  0.895589    0.24390608]
  [-0.5282003  -0.11275235  0.5418663   0.73812103]]], shape=(1, 3, 4), dtype=float32)
epoch: 150 , pr

In [37]:
model_lstm.evaluate(x,y,verbose=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - loss: 0.3972


0.3972184956073761